[build]
  base = "/site/gatsby-site"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[build.processing.html]
  pretty_urls = false

[[headers]]
  for = "/lookupindex.json"
  [headers.values]
    access-control-allow-origin = "*"

[[headers]]
  for = "/embed.js"
  [headers.values]
    access-control-allow-origin = "*"

[[redirects]]
  from = "/api/graphql"
  to = "/.netlify/functions/graphql"
  status = 200
  [redirects.rate_limit]
    # 100 requests per 60 seconds, per unique IP + domain
    window_limit = 100
    window_size = 60
    aggregate_by = ["ip", "domain"]

[[redirects]]
  from = "/api/parseNews"
  to = "/.netlify/functions/parseNews"
  status = 200

[[redirects]]
  from = "/api/semanticallyRelated"
  to = "/.netlify/functions/semanticallyRelated"
  status = 200

[[redirects]]
  from = "/api/lookupbyurl"
  to = "/.netlify/functions/lookupbyurl"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200
