[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
TERM = "xterm"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    enable = false
  [plugins.inputs.postBuild]
    enable = false
    record = true
    spa = true
    start = 'gatsby serve -p 8080'
    browser = 'chromium'