name: Cypress e2e tests

on:  
  push:
  pull_request:
    branches:
      - master
      - staging

jobs:
  install:
    name: NPM install and build site
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: site/gatsby-site
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Cache 'node_modules' and '~/.cache/Cypress' folder
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3.0.5
        env:
          cache-name: cache-install-folder
        with:
          # caching node_modules
          path: |
            site/gatsby-site/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install NPM dependencies
      - name: Install NPM dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        uses: cypress-io/github-action@v4
        with:
          working-directory: site/gatsby-site
          # just perform install
          runTests: false
          install-command: npm ci --legacy-peer-deps

      # Build Gatbsy site
      - name: Build site
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          E2E_ADMIN_USERNAME: ${{ secrets.E2E_ADMIN_USERNAME }}
          E2E_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_AVAILABLE_LANGUAGES: ${{ secrets.GATSBY_AVAILABLE_LANGUAGES }}
          GATSBY_REALM_APP_ID: ${{ secrets.GATSBY_REALM_APP_ID }}
          GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          MONGODB_REPLICA_SET: ${{ secrets.MONGODB_REPLICA_SET }}
          MONGODB_TRANSLATIONS_CONNECTION_STRING: ${{ secrets.MONGODB_TRANSLATIONS_CONNECTION_STRING }}
          MONGODB_MIGRATIONS_CONNECTION_STRING: ${{ secrets.MONGODB_MIGRATIONS_CONNECTION_STRING }}
          GATSBY_REALM_APP_GRAPHQL_URL: ${{ secrets.GATSBY_REALM_APP_GRAPHQL_URL }}

      # Extract commit hash to use as a cache key
      - name: Extract commit hash
        shell: bash
        run: echo "##[set-output name=commit;]$(echo ${GITHUB_SHA})"
        id: extract_commit_hash

      # Cache 'public' folder
      - name: Cache public folder
        uses: actions/cache@v3.0.5
        env:
          cache-name: cache-public
        with:
          path: |
            site/gatsby-site/public
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.extract_commit_hash.outputs.commit }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

  cypress-run:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    needs: install
    defaults:
      run:
        shell: bash
        working-directory: site/gatsby-site
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 10 copies of the current job in parallel
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    # stop the job if it runs over 20 minutes
    # to prevent a hanging process from using all your CI minutes
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Cache node_modules folder
      - name: Cache node modules
        id: cache-nodemodules-2
        uses: actions/cache@v3.0.5
        env:
          cache-name: cache-install-folder
        with:
          # caching node_modules
          path: |
            site/gatsby-site/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Install NPM dependencies
      - name: Install NPM dependencies
        if: steps.cache-nodemodules-2.outputs.cache-hit != 'true'
        uses: cypress-io/github-action@v4
        with:
          working-directory: site/gatsby-site
          # just perform install
          runTests: false
          install-command: npm ci --legacy-peer-deps

      # Extract commit hash to use as a cache key
      - name: Extract commit hash
        shell: bash
        run: echo "##[set-output name=commit;]$(echo ${GITHUB_SHA})"
        id: extract_commit_hash

      # Cache 'public' folder
      - name: Cache public folder
        uses: actions/cache@v3.0.5
        env:
          cache-name: cache-public
        with:
          path: |
            site/gatsby-site/public
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ steps.extract_commit_hash.outputs.commit }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Extract branch name
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: site/gatsby-site
          # we have already installed all dependencies above
          install: false
          config-file: cypress.config.js
          record: true
          parallel: true
          group: "Cypress e2e tests"
          tag: ${{ steps.extract_branch.outputs.branch }}
          start: npm run serve
          wait-on: http://localhost:8000/
          # wait for 10 minutes for the server to respond
          wait-on-timeout: 600
        env:
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          E2E_ADMIN_USERNAME: ${{ secrets.E2E_ADMIN_USERNAME }}
          E2E_ADMIN_PASSWORD: ${{ secrets.E2E_ADMIN_PASSWORD }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_AVAILABLE_LANGUAGES: ${{ secrets.GATSBY_AVAILABLE_LANGUAGES }}
          GATSBY_REALM_APP_ID: ${{ secrets.GATSBY_REALM_APP_ID }}
          GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          MONGODB_REPLICA_SET: ${{ secrets.MONGODB_REPLICA_SET }}
          MONGODB_TRANSLATIONS_CONNECTION_STRING: ${{ secrets.MONGODB_TRANSLATIONS_CONNECTION_STRING }}
          MONGODB_MIGRATIONS_CONNECTION_STRING: ${{ secrets.MONGODB_MIGRATIONS_CONNECTION_STRING }}
          GATSBY_REALM_APP_GRAPHQL_URL: ${{ secrets.GATSBY_REALM_APP_GRAPHQL_URL }}
          # Since this is triggered on a pull request, we set the commit message to the pull request title
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
